version: "3.7"

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx:stable-alpine
  #   restart: unless-stopped
  #   ports: 
  #     - "8989:80"
  #   volumes: 
  #     - ./src:/var/www/html
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php
  #     - mysql
  #   networks: 
  #     - laravel

  mysql:
    container_name: mysql
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes: 
      - ./docker/mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
    networks: 
      - laravel

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./src/.env
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    networks: 
      - laravel

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin
    restart: unless-stopped
    links:
      - mysql
    ports: 
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks: 
      - laravel

networks: 
  laravel: