version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: embras
        uid: 1000
    image: siapegov
    container_name: siapegov
    restart: unless-stopped
    # environment:
    #   APP_NAME: siapegov
    env_file:
      - ./src/.env
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    networks: 
      - siapegov

networks: 
  siapegov: